<?php if ($this->data): ?>
    <table class="datatable">
        <thead>
        <th>Field</th>
        <th>Value</th>
    </thead>
    <tbody>
        <?php foreach ($this->data as $field => $value): ?>
            <tr>
                <td><?php echo $field; ?></td>
                <td>: <?php echo $value; ?></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
    </table>
<?php else: ?>
    No data available.
<?php endif; ?>
